
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Tue Nov 06 13:28:07 CST 2018
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 48;
  static final int rw_WHILE = 20;
  static final int rw_BOOL = 19;
  static final int LBRACKET = 22;
  static final int INCREMENT = 38;
  static final int rw_IF = 15;
  static final int SLASH = 17;
  static final int rw_CONTINUE = 45;
  static final int rw_FALSE = 36;
  static final int LPAREN = 5;
  static final int SEMI = 4;
  static final int rw_PRINT = 41;
  static final int rw_TRUE = 35;
  static final int DECREMENT = 39;
  static final int MINUS = 12;
  static final int RPAREN = 6;
  static final int NOT = 37;
  static final int AND = 32;
  static final int INTLIT = 3;
  static final int rw_VOID = 24;
  static final int LT = 26;
  static final int rw_CONST = 40;
  static final int OR = 31;
  static final int COMMA = 33;
  static final int rw_ELSE = 46;
  static final int GEQ = 28;
  static final int PLUS = 11;
  static final int rw_READ = 42;
  static final int rw_INT = 18;
  static final int EOF = 0;
  static final int RBRACKET = 21;
  static final int error = 1;
  static final int COR = 29;
  static final int rw_CLASS = 34;
  static final int rw_RETURN = 43;
  static final int EQ = 13;
  static final int ASG = 7;
  static final int TIMES = 16;
  static final int CHARLIT = 49;
  static final int COLON = 10;
  static final int LBRACE = 8;
  static final int rw_CHAR = 23;
  static final int RBRACE = 9;
  static final int CAND = 30;
  static final int LEQ = 27;
  static final int rw_BREAK = 44;
  static final int INT_BITSTR = 47;
  static final int GT = 25;
  static final int NOTEQ = 14;
  static final int IDENTIFIER = 2;
}

